apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: bitnami
  pass_credentials_all: false
  password: ""
  url: https://charts.bitnami.com/bitnami
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: grafana
  pass_credentials_all: false
  password: ""
  url: https://grafana.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: minio
  pass_credentials_all: false
  password: ""
  url: https://charts.min.io/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: istio
  pass_credentials_all: false
  password: ""
  url: https://istio-release.storage.googleapis.com/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: policy-reporter
  pass_credentials_all: false
  password: ""
  url: https://kyverno.github.io/policy-reporter
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: kyverno
  pass_credentials_all: false
  password: ""
  url: https://kyverno.github.io/kyverno/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: external-secrets
  pass_credentials_all: false
  password: ""
  url: https://charts.external-secrets.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: odc
  pass_credentials_all: false
  password: ""
  url: https://opendatacube.github.io/datacube-charts/charts/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: jupyterhub
  pass_credentials_all: false
  password: ""
  url: https://jupyterhub.github.io/helm-chart/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: prometheus-community
  pass_credentials_all: false
  password: ""
  url: https://prometheus-community.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: grafana-community
  pass_credentials_all: false
  password: ""
  url: https://grafana-community.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: eoapi
  pass_credentials_all: false
  password: ""
  url: https://devseed.com/eoapi-k8s/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: knative-operator
  pass_credentials_all: false
  password: ""
  url: https://knative.github.io/operator
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: metrics-server
  pass_credentials_all: false
  password: ""
  url: https://kubernetes-sigs.github.io/metrics-server/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: eoapi-k8s
  pass_credentials_all: false
  password: ""
  url: https://devseed.com/eoapi-k8s/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: knative
  pass_credentials_all: false
  password: ""
  url: https://knative.github.io/operator
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: traefik
  pass_credentials_all: false
  password: ""
  url: https://traefik.github.io/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: hyperdx
  pass_credentials_all: false
  password: ""
  url: https://hyperdxio.github.io/helm-charts
  username: ""
