

kitty_mod ctrl+shift

scrollback_pager_history_size 1000

mouse_map ctrl+alt+left press ungrabbed mouse_selection rectangle
mouse_map b4 press grabbed,ungrabbed send_key ctrl+o
mouse_map b5 press grabbed,ungrabbed send_key ctrl+i

# tab_bar_style separator
tab_bar_edge top
# tab_bar_margin
allow_remote_control no
macos_option_as_alt yes


map cmd+shift+p command_palette

# Try to fix click to focus on unfocused OS window
# mouse_map left press ungrabbed focus


map kitty_mod+/ kitten kittens/show_keymaps.py
map kitty_mod+f1 launch --type=overlay zsh -i -c 'rg "^\s*(map|mouse_map)\s+.*" ~/.config/kitty/kitty.conf | fzf --header="Kitty Custom Binds" --reverse'


map kitty_mod+enter launch --cwd=current
map ctrl+alt+z toggle_layout stack


map cmd+t   launch --type=tab --cwd=current
enabled_layouts splits:split_axis=horizontal


show_hyperlink_targets no

map cmd+d launch --location=vsplit --cwd=current
map cmd+shift+d launch --location=hsplit --cwd=current

map cmd+shift+enter toggle_maximized

# map ctrl+cmd+, load_config_file /Users/aye011/.config/kitty/kitty.conf
# map ctrl+cmd+,  reload_config
# map ctrl+cmd+,


map kitty_mod+equal  change_font_size current +1.0
map kitty_mod+plus   change_font_size current +1.0
map kitty_mod+kp_add change_font_size current +1.0
map cmd+plus         change_font_size current +1.0
map cmd+equal        change_font_size current +1.0
map shift+cmd+equal  change_font_size current +1.0
map kitty_mod+minus       change_font_size current -1.0
map kitty_mod+kp_subtract change_font_size current -1.0
map cmd+minus             change_font_size current -1.0
map shift+cmd+minus       change_font_size current -1.0
map kitty_mod+backspace change_font_size current 0
map cmd+0               change_font_size current 0


font_size 13
# font_family      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Regular
# bold_font        family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Medium
# italic_font      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Italic
# bold_italic_font family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-MediumItalic
#

# Don't let text exist with the same foreground and background colour
# text_fg_override_threshold 4.5
# 4.5
text_composition_strategy 0.7 30
# Mac default: 1.7 30
# Linux default: 1.0 0
# <gamma adjustment, thickness of font on dark backgrounds. bigger=thicker> <multiplicative contrast>

# BEGIN_KITTY_THEME
# Gruvbox Dark Hard
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
