#!/bin/bash





#if command -v vim >/dev/null 2>&1; then
#    echo "Bootstraping Vim"
#    vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
#fi


# Install and initialise Lix (Nix)
if command -v nix &> /dev/null; then
    echo "nix is available"
else
    echo "nix is not available"
    curl -sSf -L https://install.lix.systems/lix | sh -s -- install
fi
