#:tombi:
[language-server]

actions-language-server = {command = "actions-languageserver", args = ["--stdio"]}
tilt = { command = "tilt", args = ["lsp", "start"]} #, "--debug"] }

vale-ls = {command = "vale-ls"}
ruff = {command="ruff", args=["server"]}
colours-lsp = {command="colours-lsp"}
esbonio =  {command = "esbonio"}
autoconf-language-server =  {command = "autoconf-language-server"}
make-language-server =  {command = "make-language-server"}

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]
config.harper-ls = {dialect = "Australian"}

# [language-server.harper-ls.config.harper-ls]
# # userDictPath = ""
# # fileDictPath = ""
# # diagnosticSeverity = "hint"
# # isolateEnglish = false
# dialect = "Australian"
# # maxFileLength = 120000

# [language-server.ruff.config.settings.lint]
# select = ["E", "F", "W", "B", "I", "RUF", "N", "LOG", "ERA", "W", "D", "UP", "ANN", "ASYNC", "S", "RET", "TCH", "ARG", "PTH", "DOC"]
# preview = true

[language-server.terraform-ls]
# command = "/Users/aye011/.vscode/extensions/hashicorp.terraform-2.37.7-darwin-arm64/bin/terraform-ls"
args = ["serve", "-log-file", "/Users/aye011/.cache/helix/terraform-ls.log"]
config = { terraform = { logFilePath = "/Users/aye011/.cache/helix/terraform-cli.log" } }

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config]
basedpyright.analysis.diagnosticMode = "openFilesOnly"
basedpyright.typeCheckingMode = "standard"

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validate = true
completion = true
hover = true
schemaStore.enable = true
kubernetesCRDStore.enable = true


[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"

"https://raw.githubusercontent.com/chri11g6/sops-schema/refs/heads/master/sops.schema.json" = [
  ".sops.yaml",
]

kubernetes = [
  "*deployment*.yaml",
  "*service*.yaml",
  "*configmap*.yaml",
  "*secret*.yaml",
  "*pod*.yaml",
  "*namespace*.yaml",
  "*ingress*.yaml",
]
# "https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/jsonschema/schema.json" = [
#   "*workflow*.yaml",
#   "*template*.yaml",
# ]
"https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json" = [
  "*kustomization.yaml",
  "*kustomize.yaml"
]
"https://raw.githubusercontent.com/readthedocs/readthedocs.org/master/readthedocs/rtd_tests/fixtures/spec/v2/schema.json" = [
  '/.readthedocs.yaml',
]

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[language-server.nixd.config]
nixpkgs.expr = "import (builtins.getFlake \"/Users/aye011/dev/nixos\").inputs.nixpkgs { }"
nixos.expr = "(builtins.getFlake \"/Users/aye011/dev/nixos\").nixosConfigurations.nixos.options"
home-manager.expr = "(builtins.getFlake \"/Users/aye011/.config/home-manager\").homeConfigurations.aye011.options"


[language-server.taplo.config]
# Workaround for nonsense of being nonfunctional outside git directories
# (https://github.com/helix-editor/helix/issues/3897#issuecomment-2361674437)
config = {}

[language-server.yaml-schema-router]
command = "yaml-schema-router"
args = [
  # "--log-file", "/tmp/yaml-router.log",
  # "--lsp-path", "/usr/bin/yaml-language-server"
  "--lsp-path", "/Users/aye011/.local/state/fnm_multishells/28415_1774934309616/bin/yaml-language-server"
]

[[language]]
auto-format = true
name = "nix"

[[language]]
formatter = { args = [
  "--parser",
  "markdown",
  "--prose-wrap",
  "never",        # <always|never|preserve>
], command = 'prettier' }
language-servers = ["marksman", "harper-ls"]
name = "markdown"

[[language]]
name = "python"
language-servers = ["ruff", "basedpyright"]
# formatter = { command = "ruff" , args = ["format", "-"] }
#  formatter = { command = "uvx", args = ["sh", "-c", "ruff check --fix - | ruff format -"] }


[[language]]
name = "rst"
language-servers = ["esbonio", "harper-ls"]


[[language]]
name = "make"
scope = "source.makefile"
language-servers = ["make-language-server"]

[[language]]
name = "yaml"
file-types = [
  "yml",
  "yaml",
  { glob = ".prettierrc" },
  { glob = ".clangd" },
  { glob = ".clang-format" },
  { glob = ".clang-tidy" },
  { glob = ".gem/credentials" },
  { glob = ".kube/config" },
  { glob = ".kube/kuberc" },
  { glob = "yarn.lock" },
  "sublime-syntax",
  "bu",
  { glob = ".stylelintrc" },  # https://stylelint.io/user-guide/configure/
  { glob = ".puppeteerrc" },  # https://pptr.dev/guides/configuration
   {glob = "*datacube.conf"}
]
# language-servers = [ "yaml-schema-router" ]


# [[language]]
# name = "javascript"
# formatter = { command = 'deno', args = ["fmt", "-", "--ext", "js" ] }
# auto-format = true

# [[language]]
# name = "typescript"
# formatter = { command = 'deno', args = ["fmt", "-", "--ext", "ts" ] }
# auto-format = true

# [[language]]
# name = "jsx"
# formatter = { command = 'deno', args = ["fmt", "-", "--ext", "jsx" ] }
# auto-format = true

# [[language]]
# name = "tsx"
# formatter = { command = 'deno', args = ["fmt", "-", "--ext", "tsx" ] }
# auto-format = true


# [[language]]
# name = "html"
# formatter = { command = 'prettier', args = ["--parser", "html"] }

# [[language]]
# name = "css"
# formatter = { command = 'prettier', args = ["--parser", "css"] }

# [[language]]
# name = "rust"
# auto-format = true

# roots = [
#   "Cargo.toml",
#   "Cargo.lock"
# ]

# [language.auto-pairs]
# '(' = ')'
# '{' = '}'
# '[' = ']'
# '"' = '"'
# '`' = '`'

[[language]]
name = "github-action"
scope = "source.yaml.github-action"
language-servers = [ "actions-language-server", "yaml-language-server" ]
file-types = [{ glob = ".github/workflows/*.yaml" }, { glob = ".github/workflows/*.yml" }]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
grammar = "yaml"

[[language]]
name = "d2"
scope = "source.d2"
file-types = ["d2"]
comment-tokens = "#"
roots = [""]
indent = { tab-width = 2, unit = "  " }


[[language]]
name = "kitty"
scope = "source.kitty"
file-types = [{ glob = "kitty.conf" }, { glob = ".config/kitty/*.conf" }]
comment-tokens = "#"
language-servers = ["colours-lsp"]

# https://docs.tilt.dev/editor.html
[[language]]
name = "tilt"
scope = "source.tilt"
injection-regex = "[Tt]ilt(file)?"
file-types = [{ glob = "Tiltfile" }, "tiltfile"]
comment-token = "#"
grammar = "python" # Uses starlark as grammar
indent = { tab-width = 4, unit = "    " }
language-servers = ["tilt"]
formatter = {command = "buildifier"} # Official formatter tool for starlark/bazel
auto-format = true

# Replace to hopefully make tilt work
[[language]]
name = "starlark"
scope = "source.starlark"
injection-regex = "(starlark|bzl|bazel|buck)"
file-types = ["bzl", "bazel", "star", { glob = "BUILD" }, { glob = "BUCK" }, { glob = "BUILD.*" }, { glob = "WORKSPACE" }, { glob = "WORKSPACE.bzlmod" }, { glob = "PACKAGE" }]
comment-token = "#"
indent = { tab-width = 4, unit = "    " }
language-servers = [ "starpls" ]
grammar = "python"

[[language]]
name = "prom"
scope = "source.prom"
file-types = [{ glob = "*.prom" }]
comment-tokens = "#"


[[grammar]]
source = { git = "https://github.com/ravsii/tree-sitter-d2", rev = "main" }
name = "d2"

[[grammar]]
source = { git = "https://github.com/OXY2DEV/tree-sitter-kitty", rev = "main" }
name = "kitty"


[[grammar]]
source = { git = "https://github.com/omad/tree-sitter-prom", rev = "main" }
name = "prom"
